package com.earl.timestore.entity;
// Generated 2016-4-26 18:57:26 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbCarousel generated by hbm2java
 */
public class TbCarousel implements java.io.Serializable {

	private Integer carouselid;
	private String carouselTitle;
	private Integer carouselSequence;
	private Date carouselAddtime;
	private String carouselPath;

	public TbCarousel() {
	}

	public TbCarousel(String carouselTitle, Integer carouselSequence, Date carouselAddtime, String carouselPath) {
		this.carouselTitle = carouselTitle;
		this.carouselSequence = carouselSequence;
		this.carouselAddtime = carouselAddtime;
		this.carouselPath = carouselPath;
	}

	public Integer getCarouselid() {
		return this.carouselid;
	}

	public void setCarouselid(Integer carouselid) {
		this.carouselid = carouselid;
	}

	public String getCarouselTitle() {
		return this.carouselTitle;
	}

	public void setCarouselTitle(String carouselTitle) {
		this.carouselTitle = carouselTitle;
	}

	public Integer getCarouselSequence() {
		return this.carouselSequence;
	}

	public void setCarouselSequence(Integer carouselSequence) {
		this.carouselSequence = carouselSequence;
	}

	public Date getCarouselAddtime() {
		return this.carouselAddtime;
	}

	public void setCarouselAddtime(Date carouselAddtime) {
		this.carouselAddtime = carouselAddtime;
	}

	public String getCarouselPath() {
		return this.carouselPath;
	}

	public void setCarouselPath(String carouselPath) {
		this.carouselPath = carouselPath;
	}

	@Override
	public String toString() {
		return "TbCarousel [carouselid=" + carouselid + ", carouselTitle=" + carouselTitle + ", carouselSequence="
				+ carouselSequence + ", carouselAddtime=" + carouselAddtime + ", carouselPath=" + carouselPath + "]";
	}

}
