package com.earl.timestore.entity;
// Generated 2016-4-25 12:12:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbChat generated by hbm2java
 */
public class TbChat implements java.io.Serializable {

	private Integer chatid; //id
	private TbUser tbUserByChatTo;//寄送聊天用户id
	private TbUser tbUserByChatFrom;//收到聊天用户id
	private String chatMessage;//聊天信息
	private Date chatTime;//聊天时间
	private Integer chatIssaw;//是否被查阅

	public TbChat() {
	}

	public TbChat(TbUser tbUserByChatTo, TbUser tbUserByChatFrom, String chatMessage, Date chatTime,
			Integer chatIssaw) {
		this.tbUserByChatTo = tbUserByChatTo;
		this.tbUserByChatFrom = tbUserByChatFrom;
		this.chatMessage = chatMessage;
		this.chatTime = chatTime;
		this.chatIssaw = chatIssaw;
	}

	public Integer getChatid() {
		return this.chatid;
	}

	public void setChatid(Integer chatid) {
		this.chatid = chatid;
	}

	public TbUser getTbUserByChatTo() {
		return this.tbUserByChatTo;
	}

	public void setTbUserByChatTo(TbUser tbUserByChatTo) {
		this.tbUserByChatTo = tbUserByChatTo;
	}

	public TbUser getTbUserByChatFrom() {
		return this.tbUserByChatFrom;
	}

	public void setTbUserByChatFrom(TbUser tbUserByChatFrom) {
		this.tbUserByChatFrom = tbUserByChatFrom;
	}

	public String getChatMessage() {
		return this.chatMessage;
	}

	public void setChatMessage(String chatMessage) {
		this.chatMessage = chatMessage;
	}

	public Date getChatTime() {
		return this.chatTime;
	}

	public void setChatTime(Date chatTime) {
		this.chatTime = chatTime;
	}

	public Integer getChatIssaw() {
		return this.chatIssaw;
	}

	public void setChatIssaw(Integer chatIssaw) {
		this.chatIssaw = chatIssaw;
	}

}
