package com.earl.timestore.entity;
// Generated 2016-4-25 12:12:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbComment generated by hbm2java
 */
public class TbComment implements java.io.Serializable {

	private Integer commentid;//评论id
	private TbComment tbUserByCommentParent;//父id
	private TbDemand tbDemand;//需求id
	private TbUser tbUserByCommentUser;//用户id
	private String commentContent;//评论内容
	private Date commentTime;//评论时间
	private Integer commentIssaw;//阅读状态

	public TbComment() {
	}

	public TbComment(TbComment tbUserByCommentParent, TbDemand tbDemand, TbUser tbUserByCommentUser, String commentContent,
			Date commentTime, Integer commentIssaw) {
		this.tbUserByCommentParent = tbUserByCommentParent;
		this.tbDemand = tbDemand;
		this.tbUserByCommentUser = tbUserByCommentUser;
		this.commentContent = commentContent;
		this.commentTime = commentTime;
		this.commentIssaw = commentIssaw;
	}

	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	public TbComment getTbUserByCommentParent() {
		return this.tbUserByCommentParent;
	}

	public void setTbUserByCommentParent(TbComment tbUserByCommentParent) {
		this.tbUserByCommentParent = tbUserByCommentParent;
	}

	public TbDemand getTbDemand() {
		return this.tbDemand;
	}

	public void setTbDemand(TbDemand tbDemand) {
		this.tbDemand = tbDemand;
	}

	public TbUser getTbUserByCommentUser() {
		return this.tbUserByCommentUser;
	}

	public void setTbUserByCommentUser(TbUser tbUserByCommentUser) {
		this.tbUserByCommentUser = tbUserByCommentUser;
	}

	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

	public Integer getCommentIssaw() {
		return this.commentIssaw;
	}

	public void setCommentIssaw(Integer commentIssaw) {
		this.commentIssaw = commentIssaw;
	}

	@Override
	public String toString() {
		return "TbComment [commentid=" + commentid + ", tbUserByCommentParent=" + tbUserByCommentParent + ", tbDemand="
				+ tbDemand + ", tbUserByCommentUser=" + tbUserByCommentUser + ", commentContent=" + commentContent
				+ ", commentTime=" + commentTime + ", commentIssaw=" + commentIssaw + "]";
	}

}
