package com.earl.timestore.entity;
// Generated 2016-4-26 18:57:26 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbLike generated by hbm2java
 */
public class TbLike implements java.io.Serializable {

	private Integer likeid;
	private TbUser tbUser;
	private TbDemand likeDemand;
	private Date likeTime;
	private Integer likeDeletestatus;
	private Integer likeIssaw;

	public TbLike() {
	}

	public TbLike(TbUser tbUser, TbDemand likeDemand, Date likeTime, Integer likeDeletestatus, Integer likeIssaw) {
		this.tbUser = tbUser;
		this.likeDemand = likeDemand;
		this.likeTime = likeTime;
		this.likeDeletestatus = likeDeletestatus;
		this.likeIssaw = likeIssaw;
	}

	public Integer getLikeid() {
		return this.likeid;
	}

	public void setLikeid(Integer likeid) {
		this.likeid = likeid;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public TbDemand getLikeDemand() {
		return this.likeDemand;
	}

	public void setLikeDemand(TbDemand likeDemand) {
		this.likeDemand = likeDemand;
	}

	public Date getLikeTime() {
		return this.likeTime;
	}

	public void setLikeTime(Date likeTime) {
		this.likeTime = likeTime;
	}

	public Integer getLikeDeletestatus() {
		return this.likeDeletestatus;
	}

	public void setLikeDeletestatus(Integer likeDeletestatus) {
		this.likeDeletestatus = likeDeletestatus;
	}

	public Integer getLikeIssaw() {
		return this.likeIssaw;
	}

	public void setLikeIssaw(Integer likeIssaw) {
		this.likeIssaw = likeIssaw;
	}

}
