package com.earl.timestore.entity;
// Generated 2016-4-25 12:12:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * TbRequest generated by hbm2java
 */
public class TbRequest implements java.io.Serializable {

	private Integer requestid;  //请求id
	private TbUser tbUser;//请求用户id
	private TbDemand tbDemand;//需求id
	private Date requestTime;//请求时间
	private Integer requestStatus;//请求状态
	private String requestMessage;//请求内容

	public TbRequest() {
	}

	public TbRequest(TbUser tbUser, TbDemand tbDemand, Date requestTime, Integer requestStatus, String requestMessage) {
		this.tbUser = tbUser;
		this.tbDemand = tbDemand;
		this.requestTime = requestTime;
		this.requestStatus = requestStatus;
		this.requestMessage = requestMessage;
	}

	public Integer getRequestid() {
		return this.requestid;
	}

	public void setRequestid(Integer requestid) {
		this.requestid = requestid;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public TbDemand getTbDemand() {
		return this.tbDemand;
	}

	public void setTbDemand(TbDemand tbDemand) {
		this.tbDemand = tbDemand;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public Integer getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(Integer requestStatus) {
		this.requestStatus = requestStatus;
	}

	public String getRequestMessage() {
		return this.requestMessage;
	}

	public void setRequestMessage(String requestMessage) {
		this.requestMessage = requestMessage;
	}

}
