package com.earl.timestore.entity;
// Generated 2016-4-25 12:12:32 by Hibernate Tools 3.5.0.Final

/**
 * TbSystem generated by hbm2java
 */
public class TbSystem implements java.io.Serializable {

	private Integer systemid; //系统表id
	private String systemName;//系统名称
	private String systemVersion;//系统版本
	private String systemUpdatecontent;//本次更新的内容
	private String systemAboutus;//关于我们
	private String systemContactus;//联系我们

	public TbSystem() {
	}

	public TbSystem(String systemName, String systemVersion, String systemUpdatecontent, String systemAboutus,
			String systemContactus) {
		this.systemName = systemName;
		this.systemVersion = systemVersion;
		this.systemUpdatecontent = systemUpdatecontent;
		this.systemAboutus = systemAboutus;
		this.systemContactus = systemContactus;
	}

	public Integer getSystemid() {
		return this.systemid;
	}

	public void setSystemid(Integer systemid) {
		this.systemid = systemid;
	}

	public String getSystemName() {
		return this.systemName;
	}

	public void setSystemName(String systemName) {
		this.systemName = systemName;
	}

	public String getSystemVersion() {
		return this.systemVersion;
	}

	public void setSystemVersion(String systemVersion) {
		this.systemVersion = systemVersion;
	}

	public String getSystemUpdatecontent() {
		return this.systemUpdatecontent;
	}

	public void setSystemUpdatecontent(String systemUpdatecontent) {
		this.systemUpdatecontent = systemUpdatecontent;
	}

	public String getSystemAboutus() {
		return this.systemAboutus;
	}

	public void setSystemAboutus(String systemAboutus) {
		this.systemAboutus = systemAboutus;
	}

	public String getSystemContactus() {
		return this.systemContactus;
	}

	public void setSystemContactus(String systemContactus) {
		this.systemContactus = systemContactus;
	}

}
