package com.earl.timestore.entity;
// Generated 2016-4-26 18:57:26 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUser generated by hbm2java
 */
public class TbUser implements java.io.Serializable {

	private int userId;
	private String userAccount;
	private String userPassword;
	private String userFacePath;
	private String userName;
	private String userSex;
	private Date userBirthday;
	private String userSchool;
	private Integer userLevel;
	private Integer userExperience;
	private Date userLastLoginTime;
	private String userSign;
	private Set tbLikes = new HashSet();
	private int isFake;

	public TbUser() {
	}

	public TbUser(int userId) {
		this.userId = userId;
	}

	public TbUser(int userId, String userAccount, String userPassword, String userFacePath, String userName,
			String userSex, Date userBirthday, String userSchool, Integer userLevel, Integer userExperience,
			Date userLastLoginTime, String userSign, Set tbLikes) {
		this.userId = userId;
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.userFacePath = userFacePath;
		this.userName = userName;
		this.userSex = userSex;
		this.userBirthday = userBirthday;
		this.userSchool = userSchool;
		this.userLevel = userLevel;
		this.userExperience = userExperience;
		this.userLastLoginTime = userLastLoginTime;
		this.userSign = userSign;
		this.tbLikes = tbLikes;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserFacePath() {
		return this.userFacePath;
	}

	public void setUserFacePath(String userFacePath) {
		this.userFacePath = userFacePath;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public Date getUserBirthday() {
		return this.userBirthday;
	}

	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	public String getUserSchool() {
		return this.userSchool;
	}

	public void setUserSchool(String userSchool) {
		this.userSchool = userSchool;
	}

	public Integer getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(Integer userLevel) {
		this.userLevel = userLevel;
	}

	public Integer getUserExperience() {
		return this.userExperience;
	}

	public void setUserExperience(Integer userExperience) {
		this.userExperience = userExperience;
	}

	public Date getUserLastLoginTime() {
		return this.userLastLoginTime;
	}

	public void setUserLastLoginTime(Date userLastLoginTime) {
		this.userLastLoginTime = userLastLoginTime;
	}

	public String getUserSign() {
		return this.userSign;
	}

	public void setUserSign(String userSign) {
		this.userSign = userSign;
	}

	public Set getTbLikes() {
		return this.tbLikes;
	}

	public void setTbLikes(Set tbLikes) {
		this.tbLikes = tbLikes;
	}

	public int getIsFake() {
		return isFake;
	}

	public void setIsFake(int isFake) {
		this.isFake = isFake;
	}

}
